const schema = (name) => new URL(`../schemas/${name}.schema.json`, import.meta.url);

export const SCHEMA_VERSION = "1";

export const schemaUrls = Object.freeze({
  artifactRef: schema("artifact-ref"),
  quantity: schema("quantity"),
  precisionPolicy: schema("precision-policy"),
  decimalValue: schema("decimal-value"),
  decimalAccumulation: schema("decimal-accumulation"),
  valueExpression: schema("value-expression"),
  booleanExpression: schema("boolean-expression"),
  evidence: schema("evidence"),
  claim: schema("claim"),
  ontologyCoordinate: schema("ontology-coordinate"),
  ontologyAxis: schema("ontology-axis"),
  sourceRelation: schema("source-relation"),
  clusterProvenance: schema("cluster-provenance"),
  sourceClassificationPolicy: schema("source-classification-policy"),
  sourceClassificationAnnotations: schema("source-classification-annotations"),
  sourceClassificationAdjudication: schema("source-classification-adjudication"),
  sourceClassificationView: schema("source-classification-view"),
  sourceClassifiedRelations: schema("source-classified-relations"),
  sourceNodeResolutionPolicy: schema("source-node-resolution-policy"),
  profile: schema("profile"),
  primitive: schema("primitive"),
  predicate: schema("predicate"),
  predicateNumericBinding: schema("predicate-numeric-binding"),
  predicatePlan: schema("predicate-plan"),
  identityPolicy: schema("identity-policy"),
  graphPolicy: schema("graph-policy"),
  candidate: schema("candidate"),
  skeleton: schema("skeleton"),
  skeletonEnumerationResult: schema("skeleton-enumeration-result"),
  candidateStoreSnapshot: schema("candidate-store-snapshot"),
  functional: schema("functional"),
  cohortRule: schema("cohort-rule"),
  selector: schema("selector"),
  oracleRequest: schema("oracle-request"),
  oracleRequestBinding: schema("oracle-request-binding"),
  oracleResponse: schema("oracle-response"),
  oracleValidationResult: schema("oracle-validation-result"),
  sensitivityReport: schema("sensitivity-report"),
  semanticManifest: schema("semantic-manifest"),
  runConfig: schema("run-config"),
  kernelPackage: schema("kernel-package")
});
