import assert from "node:assert/strict";
import test from "node:test";
import { schemaUrls, SCHEMA_VERSION } from "../../packages/schemas/src/index.js";

test("schema package exposes every initial contract as a file URL", () => {
  assert.equal(SCHEMA_VERSION, "1");
  assert.equal(Object.keys(schemaUrls).length, 144);
  assert.ok(
    schemaUrls.modelPackManifest.pathname.endsWith("model-pack-manifest.schema.json")
  );
  assert.ok(schemaUrls.modelPackRegistry.pathname.endsWith("model-pack-registry.schema.json"));
  assert.ok(schemaUrls.modelPackResolution.pathname.endsWith("model-pack-resolution.schema.json"));
  assert.ok(
    schemaUrls.modelPresentationDescriptor.pathname.endsWith(
      "model-presentation-descriptor.schema.json"
    )
  );
  assert.ok(
    schemaUrls.modelPresentationProjection.pathname.endsWith(
      "model-presentation-projection.schema.json"
    )
  );
  assert.ok(schemaUrls.modelLineage.pathname.endsWith("model-lineage.schema.json"));
  assert.ok(
    schemaUrls.rdfImportArtifact.pathname.endsWith("rdf-import-artifact.schema.json")
  );
  assert.ok(schemaUrls.rdfNeutralGraph.pathname.endsWith("rdf-neutral-graph.schema.json"));
  assert.ok(
    schemaUrls.shaclValidationPlan.pathname.endsWith("shacl-validation-plan.schema.json")
  );
  assert.ok(
    schemaUrls.shaclValidationReport.pathname.endsWith("shacl-validation-report.schema.json")
  );
  assert.ok(schemaUrls.rdfMappingPolicy.pathname.endsWith("rdf-mapping-policy.schema.json"));
  assert.ok(schemaUrls.rdfMappingArtifact.pathname.endsWith("rdf-mapping-artifact.schema.json"));
  assert.ok(
    schemaUrls.canonicalIdentityArtifact.pathname.endsWith(
      "canonical-identity-artifact.schema.json"
    )
  );
  assert.ok(
    schemaUrls.sourceMigrationBinding.pathname.endsWith(
      "source-migration-binding.schema.json"
    )
  );
  assert.ok(
    schemaUrls.candidateAttributeDefinition.pathname.endsWith(
      "candidate-attribute-definition.schema.json"
    )
  );
  assert.ok(
    schemaUrls.packageNullModelBaseline.pathname.endsWith(
      "package-null-model-baseline.schema.json"
    )
  );
  assert.ok(
    schemaUrls.packageProfileComposition.pathname.endsWith(
      "package-profile-composition.schema.json"
    )
  );
  assert.ok(
    schemaUrls.packageNullModelTrialSelections.pathname.endsWith(
      "package-null-model-trial-selections.schema.json"
    )
  );
  assert.ok(
    schemaUrls.invariantValue.pathname.endsWith("invariant-value.schema.json")
  );
  assert.ok(
    schemaUrls.profileSlotGuard.pathname.endsWith(
      "profile-slot-guard.schema.json"
    )
  );
  assert.ok(
    schemaUrls.decimalUnroundedAccumulation.pathname.endsWith(
      "decimal-unrounded-accumulation.schema.json"
    )
  );
  assert.ok(
    schemaUrls.candidateEnumerationInput.pathname.endsWith("candidate-enumeration-input.schema.json")
  );
  assert.ok(
    schemaUrls.candidateEnumerationResult.pathname.endsWith("candidate-enumeration-result.schema.json")
  );
  assert.ok(
    schemaUrls.packageCandidateBinding.pathname.endsWith("package-candidate-binding.schema.json")
  );
  assert.ok(
    schemaUrls.predicateGraphEvaluation.pathname.endsWith("predicate-graph-evaluation.schema.json")
  );
  assert.ok(
    schemaUrls.predicateLocalEvaluation.pathname.endsWith("predicate-local-evaluation.schema.json")
  );
  assert.ok(
    schemaUrls.perturbationDefinition.pathname.endsWith("perturbation-definition.schema.json")
  );
  assert.ok(
    schemaUrls.partialPredicateGraph.pathname.endsWith("partial-predicate-graph.schema.json")
  );
  assert.ok(
    schemaUrls.partialPredicateGraphEvaluation.pathname.endsWith(
      "partial-predicate-graph-evaluation.schema.json"
    )
  );
  assert.ok(
    schemaUrls.packagePredicateMonotonicityAudit.pathname.endsWith(
      "package-predicate-monotonicity-audit.schema.json"
    )
  );
  assert.ok(
    schemaUrls.packagePartialPruningDecision.pathname.endsWith(
      "package-partial-pruning-decision.schema.json"
    )
  );
  assert.ok(
    schemaUrls.packagePrunedCandidateGeneration.pathname.endsWith(
      "package-pruned-candidate-generation.schema.json"
    )
  );
  assert.ok(
    schemaUrls.packageGeneratorFrontierAudit.pathname.endsWith(
      "package-generator-frontier-audit.schema.json"
    )
  );
  assert.ok(
    schemaUrls.packageGeneratorFrontierDecision.pathname.endsWith(
      "package-generator-frontier-decision.schema.json"
    )
  );
  assert.ok(
    schemaUrls.packageRecursivePrunedCandidateGeneration.pathname.endsWith(
      "package-recursive-pruned-candidate-generation.schema.json"
    )
  );
  assert.ok(
    schemaUrls.packageDepthPredicateMonotonicityAudit.pathname.endsWith(
      "package-depth-predicate-monotonicity-audit.schema.json"
    )
  );
  assert.ok(
    schemaUrls.packageDepthPartialPruningDecision.pathname.endsWith(
      "package-depth-partial-pruning-decision.schema.json"
    )
  );
  assert.ok(
    schemaUrls.packageDepthPrunedCandidateGeneration.pathname.endsWith(
      "package-depth-pruned-candidate-generation.schema.json"
    )
  );
  assert.ok(
    schemaUrls.packageDepthGeneratorFrontierAudit.pathname.endsWith(
      "package-depth-generator-frontier-audit.schema.json"
    )
  );
  assert.ok(
    schemaUrls.packageDepthGeneratorFrontierDecision.pathname.endsWith(
      "package-depth-generator-frontier-decision.schema.json"
    )
  );
  assert.ok(
    schemaUrls.packageDepthRecursivePrunedCandidateGeneration.pathname.endsWith(
      "package-depth-recursive-pruned-candidate-generation.schema.json"
    )
  );
  assert.ok(
    schemaUrls.resumableCandidateEnumerationStep.pathname.endsWith(
      "resumable-candidate-enumeration-step.schema.json"
    )
  );
  assert.ok(
    schemaUrls.packageNodeFrontierAudit.pathname.endsWith(
      "package-node-frontier-audit.schema.json"
    )
  );
  assert.ok(
    schemaUrls.packageNodeFrontierDecision.pathname.endsWith(
      "package-node-frontier-decision.schema.json"
    )
  );
  assert.ok(
    schemaUrls.packageNodeGrowthPrunedCandidateGeneration.pathname.endsWith(
      "package-node-growth-pruned-candidate-generation.schema.json"
    )
  );
  assert.ok(
    schemaUrls.packageDepthNodeFrontierAudit.pathname.endsWith(
      "package-depth-node-frontier-audit.schema.json"
    )
  );
  assert.ok(
    schemaUrls.packageDepthNodeFrontierDecision.pathname.endsWith(
      "package-depth-node-frontier-decision.schema.json"
    )
  );
  assert.ok(
    schemaUrls.packageDepthNodeGrowthPrunedCandidateGeneration.pathname.endsWith(
      "package-depth-node-growth-pruned-candidate-generation.schema.json"
    )
  );
  assert.ok(
    schemaUrls.packageLevelExplanationIndex.pathname.endsWith(
      "package-level-explanation-index.schema.json"
    )
  );
  assert.ok(
    schemaUrls.packageLevelResultCensus.href.endsWith(
      "package-level-result-census.schema.json"
    )
  );
  assert.ok(
    schemaUrls.packageRunArtifactBundle.pathname.endsWith(
      "package-run-artifact-bundle.schema.json"
    )
  );
  assert.ok(
    schemaUrls.packageRunArtifactStore.pathname.endsWith(
      "package-run-artifact-store.schema.json"
    )
  );
  assert.ok(
    schemaUrls.packageRunArtifactDirectoryReceipt.pathname.endsWith(
      "package-run-artifact-directory-receipt.schema.json"
    )
  );
  assert.ok(
    schemaUrls.packageRunExecutionRecord.pathname.endsWith(
      "package-run-execution-record.schema.json"
    )
  );
  assert.ok(
    schemaUrls.packageRunExecutionRecordReceipt.pathname.endsWith(
      "package-run-execution-record-receipt.schema.json"
    )
  );
  assert.ok(
    schemaUrls.sourceNodeResolution.pathname.endsWith(
      "source-node-resolution.schema.json"
    )
  );
  assert.ok(
    schemaUrls.sourceCondensation.pathname.endsWith(
      "source-condensation.schema.json"
    )
  );
  assert.ok(
    schemaUrls.sourceMigrationReconciliation.pathname.endsWith(
      "source-migration-reconciliation.schema.json"
    )
  );
  assert.ok(
    schemaUrls.sourceMigrationMetrics.pathname.endsWith(
      "source-migration-metrics.schema.json"
    )
  );
  assert.ok(
    schemaUrls.sourceMigrationExplanationIndex.pathname.endsWith(
      "source-migration-explanation-index.schema.json"
    )
  );
  assert.ok(
    schemaUrls.sourceMigrationExplanation.pathname.endsWith(
      "source-migration-explanation.schema.json"
    )
  );
  assert.ok(
    schemaUrls.sourceClusterConcentration.pathname.endsWith(
      "source-cluster-concentration.schema.json"
    )
  );
  assert.ok(
    schemaUrls.sourceClassificationAmendments.pathname.endsWith(
      "source-classification-amendments.schema.json"
    )
  );
  assert.ok(
    schemaUrls.sourceEffectiveClassifiedRelations.pathname.endsWith(
      "source-effective-classified-relations.schema.json"
    )
  );
  assert.ok(
    schemaUrls.packageLevelCandidateExplanation.pathname.endsWith(
      "package-level-candidate-explanation.schema.json"
    )
  );
  assert.ok(schemaUrls.element.pathname.endsWith("element.schema.json"));
  assert.ok(
    schemaUrls.primitiveDepthPopulation.pathname.endsWith(
      "primitive-depth-population.schema.json"
    )
  );
  assert.ok(
    schemaUrls.packageCandidateFilterEvaluation.pathname.endsWith(
      "package-candidate-filter-evaluation.schema.json"
    )
  );
  assert.ok(
    schemaUrls.packageCandidateCensus.pathname.endsWith(
      "package-candidate-census.schema.json"
    )
  );
  assert.ok(
    schemaUrls.packageNullModelPlan.pathname.endsWith(
      "package-null-model-plan.schema.json"
    )
  );
  assert.ok(
    schemaUrls.packageNullModelProposals.pathname.endsWith(
      "package-null-model-proposals.schema.json"
    )
  );
  assert.ok(
    schemaUrls.packageNullModelTrialCensuses.pathname.endsWith(
      "package-null-model-trial-censuses.schema.json"
    )
  );
  assert.ok(
    schemaUrls.packageSelectorAdmission.pathname.endsWith(
      "package-selector-admission.schema.json"
    )
  );
  assert.ok(
    schemaUrls.packageSelectedFormations.pathname.endsWith(
      "package-selected-formations.schema.json"
    )
  );
  assert.ok(
    schemaUrls.packageDerivedProfiles.pathname.endsWith(
      "package-derived-profiles.schema.json"
    )
  );
  assert.ok(
    schemaUrls.packageDerivedDepthPopulation.pathname.endsWith(
      "package-derived-depth-population.schema.json"
    )
  );
  assert.ok(
    schemaUrls.packageDepthSourceSelection.pathname.endsWith(
      "package-depth-source-selection.schema.json"
    )
  );
  assert.ok(
    schemaUrls.packageDepthCandidateBinding.pathname.endsWith(
      "package-depth-candidate-binding.schema.json"
    )
  );
  assert.ok(
    schemaUrls.packageDepthCandidateCensus.pathname.endsWith(
      "package-depth-candidate-census.schema.json"
    )
  );
  assert.ok(
    schemaUrls.packageDepthCandidateEnumerationResult.pathname.endsWith(
      "package-depth-candidate-enumeration-result.schema.json"
    )
  );
  assert.ok(
    schemaUrls.packageDepthCandidateFilterEvaluation.pathname.endsWith(
      "package-depth-candidate-filter-evaluation.schema.json"
    )
  );
  assert.ok(
    schemaUrls.packageLevelClosure.pathname.endsWith(
      "package-level-closure.schema.json"
    )
  );
  assert.ok(
    schemaUrls.packageSelectorSensitivity.pathname.endsWith(
      "package-selector-sensitivity.schema.json"
    )
  );
  for (const url of Object.values(schemaUrls)) {
    assert.equal(url.protocol, "file:");
    assert.ok(url.pathname.endsWith(".schema.json"));
  }
});
