import assert from "node:assert/strict";
import test from "node:test";
import { verifyModelPack } from "@onto2d/model-pack";
import { buildGettyArtworkProvenanceCase } from "../../cases/getty-artwork-provenance/extract.mjs";
import { buildArtworkProvenanceRelease, verifyArtworkProvenanceRelease } from "./build.mjs";
import { compileArtworkProvenanceModelPack } from "./compiler.mjs";

test("the Artwork Provenance Model Pack reproduces its committed release", async () => { const pack = await buildArtworkProvenanceRelease(); assert.deepEqual(verifyModelPack(pack), pack); assert.deepEqual(await verifyArtworkProvenanceRelease(pack), pack); assert.equal(pack.manifest.model.id, "artwork-provenance"); assert.match(pack.manifest.model.version, /^v1-[0-9a-f]{16}$/); });
test("four exact artwork records include two equal labels without identity collapse", async () => { const pack = await buildArtworkProvenanceRelease(); const objects = pack.files["model/nodes.json"].filter((node) => node.entityKind === "artwork-record"); assert.equal(objects.length, 4); assert.equal(objects.filter((node) => node.name.endsWith("Madonna & Child")).length, 2); assert.equal(new Set(objects.map((node) => node.artworkRecordIdentity)).size, 4); });
test("native acquisition edges carry explicit non-legal semantics", async () => { const pack = await buildArtworkProvenanceRelease(); const edges = pack.files["model/edges.json"].filter((edge) => edge.evidenceClass === "getty-acquisition-part"); assert.equal(edges.length, 16); assert.ok(edges.every((edge) => edge.relationLayer === "native" && edge.legalTitleDetermination === false)); });
test("the gap is present but never becomes an asserted transfer", async () => { const pack = await buildArtworkProvenanceRelease(); const nodes = pack.files["model/nodes.json"]; const gap = nodes.find((node) => node.entityKind === "evidence-gap"); assert.deepEqual([gap.evidenceStatus, gap.contents, gap.assertedTransfer], ["unknown", null, false]); const gapEdges = pack.files["model/edges.json"].filter((edge) => edge.evidenceClass === "declared-missingness"); assert.ok(gapEdges.every((edge) => edge.assertedTransfer === false || edge.relation === "includes-gap")); });
test("all five equivalence outcomes and undefined Historical Load stay visible", async () => { const pack = await buildArtworkProvenanceRelease(); const nodes = pack.files["model/nodes.json"]; const results = new Map(nodes.filter((node) => node.entityKind === "equivalence-result").map((node) => [node.typeRole, node.result.verdict])); assert.deepEqual(Object.fromEntries(results), { "actors-unordered": "equal", "complete-evidence-chain": "unresolved", "direct-records": "equal", "gap-explicit-chain": "distinct", "physical-object": "equal" }); assert.equal(nodes.find((node) => node.typeRole === "historical-load").value, null); });
test("the compiler rejects a promoted legal-title claim", async () => { const artifact = await buildGettyArtworkProvenanceCase(); artifact.events[0].transfers[0].legalTitleDetermination = true; assert.throws(() => compileArtworkProvenanceModelPack(artifact), /legal title determination/); });
